#!/bin/sh
#
# ~/.sh/exports
#

# This file contains environment variables that are meant to be exported to the
# shell session. This file is sourced by ~/.bashrc and ~/.zshrc.

# xdg
export XDG_CONFIG_HOME="$HOME/.config"

# bat
if check bat; then
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
  export MANROFFOPT="-c"
  export PAGER="bat"
  export BAT_CONFIG_PATH="$XDG_CONFIG_HOME/bat/config"
fi

# fzf
if check fzf; then
  export FZF_DEFAULT_OPTS="--layout=reverse --border --prompt='❱ ' \
    --color=spinner:#f5e0dc,hl:#f38ba8 \
    --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
    --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"

  export FZF_TMUX=1
  export BAT_PREVIEW="bat --color=always --style=numbers --line-range=:500 {}"

  if check fd; then
    export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND="fd --type d --hidden --strip-cwd-prefix --exclude .git"
    _fzf_compgen_path() {
      fd --hidden --exclude .git . "$1"
    }
    _fzf_compgen_dir() {
      fd --dir --hidden --exclude .git . "$1"
    }
  elif check rg; then
    export FZF_DEFAULT_COMMAND="rg --files --hidden"
	else
		export FZF_DEFAULT_COMMAND="find . -regextype 'posix-extended' -iregex '\.(git|cache|node_modules).*' -type d -prune -o -print"
  fi
fi